One_Way_Anova_CBSE <- read_excel("C:/Users/Renuka/OneDrive/Documents/IACSD/Advanced_analytics/Advance Analytics-2024/Day-8_ANOVAs/One Way ANOVA/One_Way_Anova_ CBSE.xlsx")
attach(One_Way_Anova_CBSE)
str(One_Way_Anova_CBSE)
One_Way_Anova_CBSE$Stream<-as.factor(One_Way_Anova_CBSE$Stream)
str(One_Way_Anova_CBSE)
library(car)
library(carData)
leveneTest(Marks~Stream,data= One_Way_Anova_CBSE)
Model<-aov(Marks~Stream,data = One_Way_Anova_CBSE)
summary(Model)
TukeyHSD(Model)
model.tables(Model,"mean")
Model$residuals
shapiro.test(Model$residuals)
